server:
  port: 8083

app:
  jwt:
    secret: ${SECRET_JWT_TOKEN:your-256-bit-secret-key-1234567890abcdef}
  gateway:
    url: http://localhost:8080


spring:
  application:
    name: booking-service
  r2dbc:
    url: r2dbc:h2:mem:///hoteldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      management:
        context-path: /actuator

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,build,git
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.flywaydb: DEBUG