CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          room_id BIGINT NOT NULL,
                          start_date DATE NOT NULL,
                          end_date DATE NOT NULL,
                          status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT chk_dates CHECK (end_date > start_date),
                          CONSTRAINT chk_status CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

-- Индексы для производительности
CREATE INDEX idx_bookings_user_id ON bookings(user_id);
CREATE INDEX idx_bookings_room_dates ON bookings(room_id, start_date, end_date);
CREATE INDEX idx_bookings_status ON bookings(status);